Feature/neo features
neo-ngd/neo.org pull request #5
Opened 2021-04-19 16:07 UTC by rockacola

Implement "NEO Features" section of the homepage to fit newly (and easier) design (per Design Files v0.09)

Expect visual:

![image](https://user-images.githubusercontent.com/146148/115267849-fc8c4580-a17c-11eb-8f16-85c2a10676d7.png)

2021-04-26 07:00 UTC, chenzhitong commented on NeoWeb/Views/Home/_NeoFeatures.cshtml
> +      "/images/home/OneBlockFinality3D.svg", "One Block Finality", "dBFT consensus mechanism guarantees fast and efficient finality in a single block.", "technology#dbft-2.0"
Need to update resource files

2021-04-26 07:00 UTC, chenzhitong requested changes
Need to update resource files

2021-04-26 21:31 UTC, rockacola commented
Hi @chenzhitong , can you provide some guidance on how to correctly perform l18n with arrayed data object at https://github.com/neo-ngd/neo.org/blob/cd9fadbcb30a6f1c85127d91aa920f90572329b7/NeoWeb/Views/Home/_NeoFeatures.cshtml#L6-L29

I've tried to add Localizer before adding string into the array (like below), but didn't work out for me.

```cs
@{ string[,] blocks = new string[7, 4] {
  {
      "/images/home/OneBlockFinality3D.svg", Localizer["One Block Finality"].Value, Localizer["dBFT consensus mechanism guarantees fast and efficient finality in a single block."].Value, "technology#dbft-2.0"
  },
  ...
};
```

Do I need to explicit reference to the resource file somewhere?

2021-04-28 10:38 UTC, chenzhitong commented
Add `Views.Home._NeoFeatures.zh.resx` to Resources folder. @rockacola

2021-04-29 00:30 UTC, rockacola commented
@chenzhitong I've updated the resource file and its usage. It is now ready for another review. Thank you.

2021-04-29 02:22 UTC, merged